package dk.dd.grpc.grpcis.service;

import dk.dd.grpc.grpcis.client.Client;
import dk.dd.grpc.grpcis.dao.StudentDAO;
import dk.dd.grpc.grpcis.domain.Student;
import dk.dd.grpcis.stubs.student.Grade;
import dk.dd.grpcis.stubs.student.StudentRequest;
import dk.dd.grpcis.stubs.student.StudentResponse;
import dk.dd.grpcis.stubs.student.StudentServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Status;
import io.grpc.stub.StreamObserver;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class StudentService extends StudentServiceGrpc.StudentServiceImplBase
{
    // We need to have an instance of the dao class to work with the database
    private StudentDAO studentDao = new StudentDAO();
    // Let's use a logger to log everything that we want
    private static final Logger logger = Logger.getLogger(StudentService.class.getName());

    // We have to override the getStudentInfo that was defined in the StudentService class
    // The StudentService class is an autogenerated class by the proto file
    // So, let's override the getStudentInfo method here.
    @Override
    public void getStudentInfo(StudentRequest request, StreamObserver<StudentResponse> responseObserver)
    {
        String id = request.getId();// the student ID should be passed with the request message

        try{
            Student student = studentDao.findById(id); // Let's find the student information from the student table

            /*
                The getResults method will help us to fetch the results for the student from the result service.
                this method will call the result service through its client and bring back the result as a list of strings
             */
            List<String> examResponse = getResults(id);

            // Once all the results are clear, we can build our response message
            StudentResponse studentResponse = StudentResponse.newBuilder()
                    .setId(id)
                    .setName(student.getName())
                    .setMail(student.getMail())
                    .setSi(Grade.valueOf(examResponse.get(0)))
                    .setDls(Grade.valueOf(examResponse.get(1)))
                    .setTst(Grade.valueOf(examResponse.get(2)))
                    .build();
            
            responseObserver.onNext(studentResponse);
            responseObserver.onCompleted();
        }
        catch (NoSuchElementException e){
            logger.log(Level.SEVERE, "NO STUDENT FOUND WITH THE STUDENT ID :- "+ id);

            // If some error occurs we sent an error with the following status which is not_found
            responseObserver.onError(Status.NOT_FOUND.asRuntimeException());
        }
    }

    public List<String> getResults(String id)
    {
        // To connect with the Client we need a channel
        ManagedChannel channel = ManagedChannelBuilder.forTarget("localhost:8082")
                .usePlaintext()
                .build();

        Client resultClient = new Client(channel);

        return resultClient.getResults(id);
    }
}


